_welcome:
    pattern:  /
    defaults: { _controller: CorePagesBundle:Pages:index }

fos_user:
    resource: "@CoreUserBundle/Resources/config/fos_user_routing.yml"
    prefix: /

CoreTicketsBundle:
    resource: "@CoreTicketsBundle/Resources/config/routing.yml"
    prefix:   /

CorePagesBundle:
    resource: "@CorePagesBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
