CoreTicketsBundle:
    resource: "@CoreTicketsBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: CorePagesBundle:Pages:index }

CorePagesBundle:
    resource: "@CorePagesBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@CoreUserBundle/Resources/config/fos_user_routing.yml"
    prefix: /

CoreUserBundle:
    resource: "@CoreUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
