artist:
    pattern:  /
    defaults: { _controller: "CoreTicketsBundle:Artist:index" }

artist_show:
    pattern:  /{id}/show
    defaults: { _controller: "CoreTicketsBundle:Artist:show" }

artist_new:
    pattern:  /new
    defaults: { _controller: "CoreTicketsBundle:Artist:new" }

artist_create:
    pattern:  /create
    defaults: { _controller: "CoreTicketsBundle:Artist:create" }
    requirements: { _method: post }

artist_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoreTicketsBundle:Artist:edit" }

artist_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoreTicketsBundle:Artist:update" }
    requirements: { _method: post }

artist_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CoreTicketsBundle:Artist:delete" }
    requirements: { _method: post }
