tickets_list:
    pattern:  /
    defaults: { _controller: "CoreTicketsBundle:Tickets:list" }

tickets:
    pattern:  /
    defaults: { _controller: "CoreTicketsBundle:Tickets:list" }

tickets_show:
    pattern:  /{id}/show
    defaults: { _controller: "CoreTicketsBundle:Tickets:show" }

tickets_new:
    pattern:  /new
    defaults: { _controller: "CoreTicketsBundle:Tickets:new" }

tickets_create:
    pattern:  /create
    defaults: { _controller: "CoreTicketsBundle:Tickets:create" }
    requirements: { _method: post }

tickets_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoreTicketsBundle:Tickets:edit" }

tickets_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoreTicketsBundle:Tickets:update" }
    requirements: { _method: post }

tickets_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CoreTicketsBundle:Tickets:delete" }
    requirements: { _method: post }
